# Outgoing email settings

  
development:
  delivery_method: :smtp
  smtp_settings:
    address: NOEMAILSENTOUT
    port: 26
    domain: heroku.com
    authentication: :login
    user_name: ac4366312345
    password: ctvw9zfra12345
