# Outgoing email settings

production:
  delivery_method: :smtp
  smtp_settings:
    address: mail.authsmtp.com
    port: 26
    domain: heroku.com
    authentication: :login
    user_name: ac43663
    password: ctvw9zfra
  